micronaut:
  application:
    name: pnxCloud
  caches:
    github:
      expire-after-write: 10m
      maximum-size: 100
    file-cache:
      expire-after-write: 15m
      maximum-size: 100
    file-cache.isFileCached:
      expire-after-write: 7d
  server:
    cors:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3